library(readxl)
Churn_1_ <- read_excel("D:/Abhyayanam/DARET/Projects/Project 2 - Churn/Churn (1).xls")
View(Churn_1_)
save.image("D:/Abhyayanam/DARET/Projects/Project 2 - Churn/Project_2.Rdata.RData")
pchurn <- Chuurn_1_
head(pchurn,6)
sum(is.na(pchurn))
str(pchurn)
table(pchurn$Churn)
pchurn$Churn <- as.factor(pchurn$Churn)
pchurn$State <- as.factor(pchurn$State)
pchurn$Phone <- as.factor(pchurn$Phone)
pchurn$`Area Code`<- as.factor(pchurn$`Area Code`)
pchurn$`VMail Plan`<- as.factor(pchurn$`VMail Plan`)
pchurn$`Intl Plan`<- as.factor(pchurn$`Intl Plan`)
table(pchurn$State)
table(pchurn$`Area Code`)
pchurn <- pchurn[,-c(21)]
colnames(pchurn)
str(pchurn)
library(CARET)
library(caret)
library(MASS)
set.seed(246)
smp_size <- floor(0.8 * nrow(pchurn))
train_ind <- sample(seq_len(nrow(pchurn)), size = smp_size)
churntrain <- pchurn[train_ind, ]
churntest <- pchurn[-train_ind, ]
colnames(churntrain)
colnames(churntest)
nrow(churntrain)
nrow(churntest)
nrow(pchurn)
table(pchurn$Churn)
table(churntrain$Churn)
table(churntest$Churn)
fit1 <- glm(Churn~.,data = churntrain, family = binomial(link = 'logit'),control = list (maxit=50))
summary(fit1)
step_fit1 <- stepAIC(fit1,method='backward')
summary(step_fit1)
anova(fit1,test='Chisq')
anova(step_fit1, test = 'Chisq')
with(fit1, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))
with(step_fit1, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))
plot(fit1$fitted.values)
library(car)
vif(fit1)
vif(step_fit1)
trainpred1 <- predict(fit1, newdata=churntrain, type = 'response')
trainpred_step1 <- predict(step_fit1, newdata=churntrain, type = 'response')
pred1 <- predict(fit1, newdata=churntest, type = 'response')
pred_step1 <- predict(step_fit1, newdata=churntest, type = 'response')
library(pROC)
tg1 <- roc(churntrain$Churn~trainpred1, data=churntrain)
tg2 <- roc(churntrain$Churn~trainpred_step1, data=churntrain)
g1 <- roc(churntest$Churn~pred1, data = churntest)
g2 <- roc(churntest$Churn~pred_step1, data = churntest)
plot(tg1)
plot(tg2)
plot(g1)
plot(g2)
tg1
tg2
g1
g2
library(caret)
library(InformationValue)
churntrain$Pred_Churn1 <- ifelse(trainpred_step1 <0.5,0,1)
confusionMatrix(churntrain$Churn, churntrain$Pred_Churn1)
confusionMatrix(churntrain$Churn, as.factor(churntrain$Pred_Churn1))
table(churntrain$Churn)
table(churntrain$Pred_Churn1)
churntrain$Pred_Churn1 <- ifelse(trainpred_step1 <0.45,0,1)
confusionMatrix(churntrain$Churn, as.factor(churntrain$Pred_Churn1))
table(churntrain$Pred_Churn1)
churntrain$Pred_Churn1 <- ifelse(trainpred_step1 <0.40,0,1)
confusionMatrix(churntrain$Churn, as.factor(churntrain$Pred_Churn1))
table(churntrain$Pred_Churn1)
churntrain$Pred_Churn1 <- ifelse(trainpred_step1 <0.35,0,1)
confusionMatrix(churntrain$Churn, as.factor(churntrain$Pred_Churn1))
table(churntrain$Pred_Churn1)
churntrain$Pred_Churn1 <- ifelse(trainpred_step1 <0.30,0,1)
confusionMatrix(churntrain$Churn, as.factor(churntrain$Pred_Churn1))
table(churntrain$Pred_Churn1)
churntest$Pred_Churn1 <- ifelse(pred_step1 <0.50,0,1)
confusionMatrix(churntest$Churn, as.factor(churntest$Pred_Churn1))
table(churntrain$Pred_Churn1)
table(churntest$Pred_Churn1)
table(churntest$Churn)
churntest$Pred_Churn1 <- ifelse(pred_step1 < 0.30,0,1)
table(churntest$Pred_Churn1)
confusionMatrix(churntest$Churn, as.factor(churntest$Pred_Churn1))
churntest$Pred_Churn1 <- ifelse(pred_step1 < 0.35,0,1)
confusionMatrix(churntest$Churn, as.factor(churntest$Pred_Churn1))
table(churntest$Pred_Churn1)
churntest$Pred_Churn1 <- ifelse(pred_step1 < 0.28,0,1)
table(churntest$Pred_Churn1)
confusionMatrix(churntest$Churn, as.factor(churntest$Pred_Churn1))
